from . import account_journal
from . import account_invoice
from . import account_tax
from . import ir_actions_report
from . import res_config_settings
from . import payment_acquirer
from . import res_partner
from . import res_currency
from . import uom
